/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/alignment-baseline'                          > svg_attributes_alignment-baseline.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/baseline-shift'                              > svg_attributes_baseline-shift.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/clip-rule'                                   > svg_attributes_clip-rule.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/color-interpolation-filters'                 > svg_attributes_color-interpolation-filters.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/dominant-baseline'                           > svg_attributes_dominant-baseline.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/enable-background'                           > svg_attributes_enable-background.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/fill'                                        > svg_attributes_fill.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/fill-opacity'                                > svg_attributes_fill-opacity.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/fill-rule'                                   > svg_attributes_fill-rule.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/flood-color'                                 > svg_attributes_flood-color.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/flood-opacity'                               > svg_attributes_flood-opacity.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/glyph-orientation-horizontal'                > svg_attributes_glyph-orientation-horizontal.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/glyph-orientation-vertical'                  > svg_attributes_glyph-orientation-vertical.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/kerning'                                     > svg_attributes_kerning.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/lighting-color'                              > svg_attributes_lighting-color.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/marker'                                      > svg_attributes_marker.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/marker-end'                                  > svg_attributes_marker-end.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/marker-mid'                                  > svg_attributes_marker-mid.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/marker-start'                                > svg_attributes_marker-start.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/mask'                                        > svg_attributes_mask.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/pointers'                                    > svg_attributes_pointers.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/stop-color'                                  > svg_attributes_stop-color.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/stop-opacity'                                > svg_attributes_stop-opacity.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/stroke'                                      > svg_attributes_stroke.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/stroke-dasharray'                            > svg_attributes_stroke-dasharray.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/stroke-dashoffset'                           > svg_attributes_stroke-dashoffset.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/stroke-linecap'                              > svg_attributes_stroke-linecap.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/stroke-linejoin'                             > svg_attributes_stroke-linejoin.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/stroke-miterlimit'                           > svg_attributes_stroke-miterlimit.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/stroke-opacity'                              > svg_attributes_stroke-opacity.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/stroke-width'                                > svg_attributes_stroke-width.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/attributes/text-anchor'                                 > svg_attributes_text-anchor.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/a'                                             > svg_elements_a.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/circle'                                        > svg_elements_circle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/clipPath'                                      > svg_elements_clipPath.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/defs'                                          > svg_elements_defs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/desc'                                          > svg_elements_desc.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/ellipse'                                       > svg_elements_ellipse.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/etextContent'                                  > svg_elements_etextContent.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feBlend'                                       > svg_elements_feBlend.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feColorMatrix'                                 > svg_elements_feColorMatrix.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feColorMatrix'                                    > svg_elements_feColorMatrix.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feComponentTransfer'                           > svg_elements_feComponentTransfer.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feComposite'                                   > svg_elements_feComposite.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feConvolveMatrix'                              > svg_elements_feConvolveMatrix.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feDiffuseLighting'                             > svg_elements_feDiffuseLighting.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feDisplacementMap'                             > svg_elements_feDisplacementMap.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feDistantLight'                                > svg_elements_feDistantLight.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feFlood'                                       > svg_elements_feFlood.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feFuncA'                                       > svg_elements_feFuncA.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feFuncB'                                       > svg_elements_feFuncB.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feFuncG'                                       > svg_elements_feFuncG.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feFuncG'                                > svg_elements_feFuncG.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feFuncR'                                       > svg_elements_feFuncR.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feGaussianBlur'                                > svg_elements_feGaussianBlur.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feImage'                                       > svg_elements_feImage.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feMerge'                                       > svg_elements_feMerge.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feMergeNode'                                   > svg_elements_feMergeNode.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feMorphology'                                  > svg_elements_feMorphology.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feOffset'                                      > svg_elements_feOffset.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/fePointLight'                                  > svg_elements_fePointLight.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feSpecularLighting'                            > svg_elements_feSpecularLighting.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feSpotlight'                                   > svg_elements_feSpotlight.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feTile'                                        > svg_elements_feTile.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/feTurbulence'                                  > svg_elements_feTurbulence.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/filter'                                        > svg_elements_filter.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/g'                                             > svg_elements_g.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/gradient'                                      > svg_elements_gradient.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/image'                                         > svg_elements_image.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/line'                                          > svg_elements_line.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/linearGradient'                                > svg_elements_linearGradient.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/marker'                                        > svg_elements_marker.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/mask'                                          > svg_elements_mask.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/metadata'                                      > svg_elements_metadata.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/path'                                          > svg_elements_path.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/patterrn'                                      > svg_elements_patterrn.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/polygon'                                       > svg_elements_polygon.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/polyline'                                      > svg_elements_polyline.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/radialGradient'                                > svg_elements_radialGradient.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/rect'                                          > svg_elements_rect.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/script'                                        > svg_elements_script.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/stop'                                          > svg_elements_stop.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/style'                                         > svg_elements_style.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/svg'                                           > svg_elements_svg.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/switch'                                        > svg_elements_switch.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/symbol'                                        > svg_elements_symbol.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/text'                                          > svg_elements_text.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/textPath'                                      > svg_elements_textPath.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/textPositioning'                               > svg_elements_textPositioning.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/title'                                         > svg_elements_title.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/tspan'                                         > svg_elements_tspan.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/use'                                           > svg_elements_use.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/elements/view'                                          > svg_elements_view.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/events/error'                                           > svg_events_error.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/events/load'                                            > svg_events_load.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/events/onabort'                                         > svg_events_onabort.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/events/onzoom'                                          > svg_events_onzoom.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/events/resize'                                          > svg_events_resize.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/events/scroll'                                          > svg_events_scroll.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/events/unload'                                          > svg_events_unload.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/addListener'                                    > svg_methods_addListener.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/animationsPaused'                               > svg_methods_animationsPaused.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/appendItem'                                     > svg_methods_appendItem.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/checkEnclosure'                                 > svg_methods_checkEnclosure.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/checkIntersection'                              > svg_methods_checkIntersection.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/clear'                                          > svg_methods_clear.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/consolidate'                                    > svg_methods_consolidate.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/convertToSpecifiedUnits'                        > svg_methods_convertToSpecifiedUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/create'                                         > svg_methods_create.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGAngle'                                 > svg_methods_createSVGAngle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGLength'                                > svg_methods_createSVGLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGMatrix'                                > svg_methods_createSVGMatrix.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGNumber'                                > svg_methods_createSVGNumber.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegArcAbs'                         > svg_methods_createSVGPathSegArcAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegArcRel'                         > svg_methods_createSVGPathSegArcRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegClosePath'                      > svg_methods_createSVGPathSegClosePath.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegCurvetoCubicAbs'                > svg_methods_createSVGPathSegCurvetoCubicAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegCurvetoCubicRel'                > svg_methods_createSVGPathSegCurvetoCubicRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegCurvetoCubicSmoothAbs'          > svg_methods_createSVGPathSegCurvetoCubicSmoothAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegCurvetoCubicSmoothRel'          > svg_methods_createSVGPathSegCurvetoCubicSmoothRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegCurvetoQuadraticAbs'            > svg_methods_createSVGPathSegCurvetoQuadraticAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegCurvetoQuadraticRel'            > svg_methods_createSVGPathSegCurvetoQuadraticRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegCurvetoQuadraticSmoothAbs'      > svg_methods_createSVGPathSegCurvetoQuadraticSmoothAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegCurvetoQuadraticSmoothRel'      > svg_methods_createSVGPathSegCurvetoQuadraticSmoothRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegLinetoAbs'                      > svg_methods_createSVGPathSegLinetoAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegLinetoHorizontalAbs'            > svg_methods_createSVGPathSegLinetoHorizontalAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegLinetoHorizontalRel'            > svg_methods_createSVGPathSegLinetoHorizontalRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegLinetoRel'                      > svg_methods_createSVGPathSegLinetoRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegLinetoVerticalAbs'              > svg_methods_createSVGPathSegLinetoVerticalAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegLinetoVerticalRel'              > svg_methods_createSVGPathSegLinetoVerticalRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegMovetoAbs'                      > svg_methods_createSVGPathSegMovetoAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPathSegMovetoRel'                      > svg_methods_createSVGPathSegMovetoRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGPoint'                                 > svg_methods_createSVGPoint.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGRect'                                  > svg_methods_createSVGRect.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGTransform'                             > svg_methods_createSVGTransform.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/createSVGTransformFromMatrix'                   > svg_methods_createSVGTransformFromMatrix.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/deselectAll'                                    > svg_methods_deselectAll.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/dispatchEvent'                                  > svg_methods_dispatchEvent.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/flipX'                                          > svg_methods_flipX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/flipY'                                          > svg_methods_flipY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/forceRedraw'                                    > svg_methods_forceRedraw.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getBBox'                                        > svg_methods_getBBox.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getCTM'                                         > svg_methods_getCTM.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getCharNumAtPosition'                           > svg_methods_getCharNumAtPosition.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getComputedStyle'                               > svg_methods_getComputedStyle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getComputedTextLength'                          > svg_methods_getComputedTextLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getCurrentTime'                                 > svg_methods_getCurrentTime.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getElementById'                                 > svg_methods_getElementById.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getEnclosureList'                               > svg_methods_getEnclosureList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getEndPositionOfChar'                           > svg_methods_getEndPositionOfChar.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getExtentOfChar'                                > svg_methods_getExtentOfChar.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getIntersectionList'                            > svg_methods_getIntersectionList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getItem'                                        > svg_methods_getItem.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getNumberOfChars'                               > svg_methods_getNumberOfChars.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getPathSegAtLength'                             > svg_methods_getPathSegAtLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getPointAtLength'                               > svg_methods_getPointAtLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getRotationOfChar'                              > svg_methods_getRotationOfChar.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getSVGDocument'                                 > svg_methods_getSVGDocument.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getScreenCTM'                                   > svg_methods_getScreenCTM.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getStartPositionOfChar'                         > svg_methods_getStartPositionOfChar.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getSubStringLength'                             > svg_methods_getSubStringLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getTotalLength'                                 > svg_methods_getTotalLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/getTransformToElement'                          > svg_methods_getTransformToElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/hasExtension'                                   > svg_methods_hasExtension.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/initialize'                                     > svg_methods_initialize.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/insertItemBefore'                               > svg_methods_insertItemBefore.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/inverse'                                        > svg_methods_inverse.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/item'                                           > svg_methods_item.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/matrixTransform'                                > svg_methods_matrixTransform.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/multiply'                                       > svg_methods_multiply.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/newValueSpecifiedUnits'                         > svg_methods_newValueSpecifiedUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/pauseAnimations'                                > svg_methods_pauseAnimations.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/removeItem'                                     > svg_methods_removeItem.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/removeListener'                                 > svg_methods_removeListener.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/replaceItem'                                    > svg_methods_replaceItem.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/rotate'                                         > svg_methods_rotate.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/rotateFromVector'                               > svg_methods_rotateFromVector.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/scale'                                          > svg_methods_scale.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/scaleNonUniform'                                > svg_methods_scaleNonUniform.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/selectSubString'                                > svg_methods_selectSubString.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setCurrentTime'                                 > svg_methods_setCurrentTime.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setFilterRes'                                   > svg_methods_setFilterRes.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setMatrix'                                      > svg_methods_setMatrix.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setOrientToAngle'                               > svg_methods_setOrientToAngle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setOrientToAuto'                                > svg_methods_setOrientToAuto.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setRotate'                                      > svg_methods_setRotate.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setScale'                                       > svg_methods_setScale.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setSkewX'                                       > svg_methods_setSkewX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setSkewY'                                       > svg_methods_setSkewY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setStdDeviation'                                > svg_methods_setStdDeviation.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/setTranslate'                                   > svg_methods_setTranslate.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/skewX'                                          > svg_methods_skewX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/skewY'                                          > svg_methods_skewY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/suspendRedraw'                                  > svg_methods_suspendRedraw.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/toString'                                       > svg_methods_toString.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/translate'                                      > svg_methods_translate.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/unpauseAnimations'                              > svg_methods_unpauseAnimations.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/unsuspendRedraw'                                > svg_methods_unsuspendRedraw.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/methods/unsuspendRedrawAll'                             > svg_methods_unsuspendRedrawAll.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAngle'                                       > svg_objects_SVGAngle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedAngle'                               > svg_objects_SVGAnimatedAngle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedBoolean'                             > svg_objects_SVGAnimatedBoolean.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedEnumeration'                         > svg_objects_SVGAnimatedEnumeration.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedInteger'                             > svg_objects_SVGAnimatedInteger.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedLength'                              > svg_objects_SVGAnimatedLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedLengthList'                          > svg_objects_SVGAnimatedLengthList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedNumber'                              > svg_objects_SVGAnimatedNumber.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedNumberList'                          > svg_objects_SVGAnimatedNumberList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedPreserveAspectRatio'                 > svg_objects_SVGAnimatedPreserveAspectRatio.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedRect'                                > svg_objects_SVGAnimatedRect.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedString'                              > svg_objects_SVGAnimatedString.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedStringNS'                            > svg_objects_SVGAnimatedStringNS.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGAnimatedTransformList'                       > svg_objects_SVGAnimatedTransformList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGComponentTransferFunctionElement'            > svg_objects_SVGComponentTransferFunctionElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGElement'                                     > svg_objects_SVGElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGElementInstance'                             > svg_objects_SVGElementInstance.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGElementInstanceList'                         > svg_objects_SVGElementInstanceList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGException'                                   > svg_objects_SVGException.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGLength'                                      > svg_objects_SVGLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGLengthList'                                  > svg_objects_SVGLengthList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGMatrix'                                      > svg_objects_SVGMatrix.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGNumber'                                      > svg_objects_SVGNumber.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGNumberList'                                  > svg_objects_SVGNumberList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPath'                                        > svg_objects_SVGPath.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSeg'                                     > svg_objects_SVGPathSeg.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegArcAbs'                               > svg_objects_SVGPathSegArcAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegArcRel'                               > svg_objects_SVGPathSegArcRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegClosePath'                            > svg_objects_SVGPathSegClosePath.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegCurvetoCubicAbs'                      > svg_objects_SVGPathSegCurvetoCubicAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegCurvetoCubicRel'                      > svg_objects_SVGPathSegCurvetoCubicRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegCurvetoCubicSmoothAbs'                > svg_objects_SVGPathSegCurvetoCubicSmoothAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegCurvetoCubicSmoothRel'                > svg_objects_SVGPathSegCurvetoCubicSmoothRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegCurvetoQuadraticAbs'                  > svg_objects_SVGPathSegCurvetoQuadraticAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegCurvetoQuadraticRel'                  > svg_objects_SVGPathSegCurvetoQuadraticRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegCurvetoQuadraticSmoothAbs'            > svg_objects_SVGPathSegCurvetoQuadraticSmoothAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegCurvetoQuadraticSmoothRel'            > svg_objects_SVGPathSegCurvetoQuadraticSmoothRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegLinetoAbs'                            > svg_objects_SVGPathSegLinetoAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegLinetoHorizontalAbs'                  > svg_objects_SVGPathSegLinetoHorizontalAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegLinetoHorizontalRel'                  > svg_objects_SVGPathSegLinetoHorizontalRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegLinetoRel'                            > svg_objects_SVGPathSegLinetoRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegLinetoVerticalAbs'                    > svg_objects_SVGPathSegLinetoVerticalAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegLinetoVerticalRel'                    > svg_objects_SVGPathSegLinetoVerticalRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegList'                                 > svg_objects_SVGPathSegList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegMovetoAbs'                            > svg_objects_SVGPathSegMovetoAbs.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPathSegMovetoRel'                            > svg_objects_SVGPathSegMovetoRel.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPoint'                                       > svg_objects_SVGPoint.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPointList'                                   > svg_objects_SVGPointList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGPreserveAspectRatio'                         > svg_objects_SVGPreserveAspectRatio.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGRect'                                        > svg_objects_SVGRect.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGStringList'                                  > svg_objects_SVGStringList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGTransform'                                   > svg_objects_SVGTransform.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGTransformList'                               > svg_objects_SVGTransformList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGZoom'                                        > svg_objects_SVGZoom.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/objects/SVGZoomAndPan'                                  > svg_objects_SVGZoomAndPan.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/a'                                           > svg_properties_a.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/align'                                       > svg_properties_align.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/amplitude'                                   > svg_properties_amplitude.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/angle'                                       > svg_properties_angle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedAngle)'                  > svg_properties_animVal_SVGAnimatedAngle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedBoolean)'                > svg_properties_animVal_SVGAnimatedBoolean.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedEnumeration)'            > svg_properties_animVal_SVGAnimatedEnumeration.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedInteger)'                > svg_properties_animVal_SVGAnimatedInteger.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedLength)'                 > svg_properties_animVal_SVGAnimatedLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedLengthList)'             > svg_properties_animVal_SVGAnimatedLengthList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedNumber)'                 > svg_properties_animVal_SVGAnimatedNumber.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedNumberList)'             > svg_properties_animVal_SVGAnimatedNumberList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedPreserveAspectRatio)'    > svg_properties_animVal_SVGAnimatedPreserveAspectRatio.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedRect)'                   > svg_properties_animVal_SVGAnimatedRect.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedString)'                 > svg_properties_animVal_SVGAnimatedString.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animVal_(SVGAnimatedTransformList)'          > svg_properties_animVal_SVGAnimatedTransformList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animatedInstanceRoot'                        > svg_properties_animatedInstanceRoot.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animatedNormalizedPathSegList'               > svg_properties_animatedNormalizedPathSegList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animatedPathSegList'                         > svg_properties_animatedPathSegList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/animatedPoints'                              > svg_properties_animatedPoints.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/azimuth'                                     > svg_properties_azimuth.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/b'                                           > svg_properties_b.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseFrequencyX'                              > svg_properties_baseFrequencyX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseFrequencyY'                              > svg_properties_baseFrequencyY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedAngle)'                  > svg_properties_baseVal_SVGAnimatedAngle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedBoolean)'                > svg_properties_baseVal_SVGAnimatedBoolean.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedEnumeration)'            > svg_properties_baseVal_SVGAnimatedEnumeration.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedInteger)'                > svg_properties_baseVal_SVGAnimatedInteger.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedLength)'                 > svg_properties_baseVal_SVGAnimatedLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedLengthList)'             > svg_properties_baseVal_SVGAnimatedLengthList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedNumber)'                 > svg_properties_baseVal_SVGAnimatedNumber.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedNumberList)'             > svg_properties_baseVal_SVGAnimatedNumberList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedPreserveAspectRatio)'    > svg_properties_baseVal_SVGAnimatedPreserveAspectRatio.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedRect)'                   > svg_properties_baseVal_SVGAnimatedRect.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedString)'                 > svg_properties_baseVal_SVGAnimatedString.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/baseVal_(SVGAnimatedTransformList)'          > svg_properties_baseVal_SVGAnimatedTransformList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/bias'                                        > svg_properties_bias.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/c'                                           > svg_properties_c.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/childNodes'                                  > svg_properties_childNodes.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/className'                                   > svg_properties_className.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/clipPath'                                    > svg_properties_clipPath.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/clipPathUnits'                               > svg_properties_clipPathUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/code'                                        > svg_properties_code.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/contentScriptType'                           > svg_properties_contentScriptType.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/contentStyleType'                            > svg_properties_contentStyleType.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/correspondingElement'                        > svg_properties_correspondingElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/correspondingUseElement'                     > svg_properties_correspondingUseElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/currentScale'                                > svg_properties_currentScale.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/currentTranslate'                            > svg_properties_currentTranslate.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/currentView'                                 > svg_properties_currentView.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/cx'                                          > svg_properties_cx.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/cx_(SVGRadialGradientElement)'               > svg_properties_cx_SVGRadialGradientElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/cy'                                          > svg_properties_cy.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/cy_(SVGRadialGradientElement)'               > svg_properties_cy_SVGRadialGradientElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/d'                                           > svg_properties_d.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/diffuseConstant'                             > svg_properties_diffuseConstant.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/divisor'                                     > svg_properties_divisor.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/dx'                                          > svg_properties_dx.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/dy'                                          > svg_properties_dy.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/e'                                           > svg_properties_e.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/edgeMode'                                    > svg_properties_edgeMode.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/elevation'                                   > svg_properties_elevation.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/exponent'                                    > svg_properties_exponent.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/externalResourcesRequired'                   > svg_properties_externalResourcesRequired.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/f'                                           > svg_properties_f.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/farthestViewportElement'                     > svg_properties_farthestViewportElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/filter'                                      > svg_properties_filter.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/filterResX'                                  > svg_properties_filterResX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/filterResY'                                  > svg_properties_filterResY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/filterUnits'                                 > svg_properties_filterUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/firstChild'                                  > svg_properties_firstChild.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/focusable'                                   > svg_properties_focusable.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/fx'                                          > svg_properties_fx.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/fy'                                          > svg_properties_fy.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/gradientTransform'                           > svg_properties_gradientTransform.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/gradientUnits'                               > svg_properties_gradientUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/height'                                      > svg_properties_height.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/href'                                        > svg_properties_href.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/id'                                          > svg_properties_id.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/in1'                                         > svg_properties_in1.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/in2'                                         > svg_properties_in2.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/instanceRoot'                                > svg_properties_instanceRoot.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/intercept'                                   > svg_properties_intercept.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/k1'                                          > svg_properties_k1.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/k2'                                          > svg_properties_k2.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/k3'                                          > svg_properties_k3.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/k4'                                          > svg_properties_k4.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/kernelMatrix'                                > svg_properties_kernelMatrix.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/kernelUnitLengthX'                           > svg_properties_kernelUnitLengthX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/kernelUnitLengthY'                           > svg_properties_kernelUnitLengthY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/largeArcFlag'                                > svg_properties_largeArcFlag.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/lastChild'                                   > svg_properties_lastChild.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/length'                                      > svg_properties_length.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/lengthAdjust'                                > svg_properties_lengthAdjust.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/limitingConeAngle'                           > svg_properties_limitingConeAngle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/markerHeight'                                > svg_properties_markerHeight.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/markerUnits'                                 > svg_properties_markerUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/markerWidth'                                 > svg_properties_markerWidth.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/maskContentUnits'                            > svg_properties_maskContentUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/maskUnits'                                   > svg_properties_maskUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/matrix'                                      > svg_properties_matrix.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/media'                                       > svg_properties_media.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/meetOrSlice'                                 > svg_properties_meetOrSlice.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/message'                                     > svg_properties_message.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/mode'                                        > svg_properties_mode.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/name'                                        > svg_properties_name.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/nearestViewportElement'                      > svg_properties_nearestViewportElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/newScale'                                    > svg_properties_newScale.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/newTranslate'                                > svg_properties_newTranslate.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/nextSibling'                                 > svg_properties_nextSibling.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/normalizedPathSegList'                       > svg_properties_normalizedPathSegList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/numOctaves'                                  > svg_properties_numOctaves.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/numberOfItems'                               > svg_properties_numberOfItems.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/offset'                                      > svg_properties_offset.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/operator'                                    > svg_properties_operator.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/orderX'                                      > svg_properties_orderX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/orderY'                                      > svg_properties_orderY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/orientAngle'                                 > svg_properties_orientAngle.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/orientType'                                  > svg_properties_orientType.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/ownerSVGElement'                             > svg_properties_ownerSVGElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/parentNode'                                  > svg_properties_parentNode.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/pathLength'                                  > svg_properties_pathLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/pathSegList'                                 > svg_properties_pathSegList.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/pathSegType'                                 > svg_properties_pathSegType.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/pathSegTypeAsLetter'                         > svg_properties_pathSegTypeAsLetter.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/patternContentUnits'                         > svg_properties_patternContentUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/patternTransform'                            > svg_properties_patternTransform.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/patternUnits'                                > svg_properties_patternUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/pixelUnitToMillimeterX'                      > svg_properties_pixelUnitToMillimeterX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/pixelUnitToMillimeterY'                      > svg_properties_pixelUnitToMillimeterY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/points'                                      > svg_properties_points.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/pointsAtX'                                   > svg_properties_pointsAtX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/pointsAtY'                                   > svg_properties_pointsAtY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/pointsAtZ'                                   > svg_properties_pointsAtZ.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/preserveAlpha'                               > svg_properties_preserveAlpha.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/preserveAspectRatio'                         > svg_properties_preserveAspectRatio.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/previousScale'                               > svg_properties_previousScale.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/previousSibling'                             > svg_properties_previousSibling.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/previousTranslate'                           > svg_properties_previousTranslate.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/primitiveUnits'                              > svg_properties_primitiveUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/r'                                           > svg_properties_r.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/r1'                                          > svg_properties_r1.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/r2'                                          > svg_properties_r2.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/r_(SVGRadialGradientElement)'                > svg_properties_r_SVGRadialGradientElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/radiusX'                                     > svg_properties_radiusX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/radiusY'                                     > svg_properties_radiusY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/refX'                                        > svg_properties_refX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/refY'                                        > svg_properties_refY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/requiredExtensions'                          > svg_properties_requiredExtensions.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/requiredFeatures'                            > svg_properties_requiredFeatures.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/result'                                      > svg_properties_result.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/rootElement'                                 > svg_properties_rootElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/rotate'                                      > svg_properties_rotate.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/rx_(SVGEllipseElement)'                      > svg_properties_rx_SVGEllipseElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/rx_(SVGRectElement)'                         > svg_properties_rx_SVGRectElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/ry_(SVGEllipseElement)'                      > svg_properties_ry_SVGEllipseElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/ry_(SVGRectElement)'                         > svg_properties_ry_SVGRectElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/screenPixelToMillimeterX'                    > svg_properties_screenPixelToMillimeterX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/screenPixelToMillimeterY'                    > svg_properties_screenPixelToMillimeterY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/seed'                                        > svg_properties_seed.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/slope'                                       > svg_properties_slope.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/spacing'                                     > svg_properties_spacing.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/specularConstant'                            > svg_properties_specularConstant.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/specularExponent'                            > svg_properties_specularExponent.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/spread'                                      > svg_properties_spread.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/startOffset'                                 > svg_properties_startOffset.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/stdDeviationX'                               > svg_properties_stdDeviationX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/stdDeviationY'                               > svg_properties_stdDeviationY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/stitchTiles'                                 > svg_properties_stitchTiles.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/style'                                       > svg_properties_style.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/surfaceScale'                                > svg_properties_surfaceScale.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/sweepFlag'                                   > svg_properties_sweepFlag.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/systemLanguage'                              > svg_properties_systemLanguage.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/tableValues'                                 > svg_properties_tableValues.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/target'                                      > svg_properties_target.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/targetX'                                     > svg_properties_targetX.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/targetY'                                     > svg_properties_targetY.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/textLength'                                  > svg_properties_textLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/title'                                       > svg_properties_title.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/transform'                                   > svg_properties_transform.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/type_(SVGComponentTransferFunctionElement)'  > svg_properties_type_SVGComponentTransferFunctionElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/type_(SVGFEColorMatrixElement)'              > svg_properties_type_SVGFEColorMatrixElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/type_(SVGFETurbulenceElement)'               > svg_properties_type_SVGFETurbulenceElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/type_(SVGScriptElement)'                     > svg_properties_type_SVGScriptElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/type_(SVGStyleElement)'                      > svg_properties_type_SVGStyleElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/type_(SVGTransform)'                         > svg_properties_type_SVGTransform.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/unitType'                                    > svg_properties_unitType.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/unitType_(SVGLength)'                        > svg_properties_unitType_SVGLength.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/useCurrentView'                              > svg_properties_useCurrentView.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/value'                                       > svg_properties_value.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/valueAsString'                               > svg_properties_valueAsString.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/valueInSpecifiedUnits'                       > svg_properties_valueInSpecifiedUnits.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/values'                                      > svg_properties_values.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/viewBox'                                     > svg_properties_viewBox.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/viewTarget'                                  > svg_properties_viewTarget.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/viewport'                                    > svg_properties_viewport.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/viewportElement'                             > svg_properties_viewportElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/width'                                       > svg_properties_width.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/x'                                           > svg_properties_x.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/x1'                                          > svg_properties_x1.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/x1_(SVGLineElement)'                         > svg_properties_x1_SVGLineElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/x1_(SVGLinearGradientElement)'               > svg_properties_x1_SVGLinearGradientElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/x2'                                          > svg_properties_x2.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/x2_(SVGLineElement)'                         > svg_properties_x2_SVGLineElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/x2_(SVGLinearGradientElement)'               > svg_properties_x2_SVGLinearGradientElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/xChannelSelector'                            > svg_properties_xChannelSelector.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/xmlbase'                                     > svg_properties_xmlbase.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/xmllang'                                     > svg_properties_xmllang.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/xmlspace'                                    > svg_properties_xmlspace.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/y'                                           > svg_properties_y.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/y1'                                          > svg_properties_y1.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/y1_(SVGLineElement)'                         > svg_properties_y1_SVGLineElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/y1_(SVGLinearGradientElement)'               > svg_properties_y1_SVGLinearGradientElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/y2'                                          > svg_properties_y2.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/y2_(SVGLineElement)'                         > svg_properties_y2_SVGLineElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/y2_(SVGLinearGradientElement)'               > svg_properties_y2_SVGLinearGradientElement.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/yChannelSelector'                            > svg_properties_yChannelSelector.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/z'                                           > svg_properties_z.txt
/Users/sierra/sandbox/webplatform/src/wpdget.pl get 'svg/properties/zoomAndPan'                                  > svg_properties_zoomAndPan.txt

