/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/Animations_in_SVG > _svg_Animations_in_SVG
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/Building_SVG_paths > _svg_Building_SVG_paths
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/External_content_in_SVG > _svg_External_content_in_SVG
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/Fills_and_strokes_in_SVG > _svg_Fills_and_strokes_in_SVG
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/SVG_clipping_and_masking > _svg_SVG_clipping_and_masking
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/SVG_filters > _svg_SVG_filters
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/SVG_fonts > _svg_SVG_fonts
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/SVG_gradients > _svg_SVG_gradients
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/SVG_image_element > _svg_SVG_image_element
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/SVG_introduction > _svg_SVG_introduction
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/SVG_links > _svg_SVG_links
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/SVG_pattern_fills > _svg_SVG_pattern_fills
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/SVG_syntax_and_deployment > _svg_SVG_syntax_and_deployment
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/Scripting_SVG > _svg_Scripting_SVG
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/Styling_SVG_with_CSS > _svg_Styling_SVG_with_CSS
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/Using_text_in_SVG > _svg_Using_text_in_SVG
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/animations_in_svg > _svg_animations_in_svg
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/building_svg_paths > _svg_building_svg_paths
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/external_content_in_svg > _svg_external_content_in_svg
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/fills_and_strokes_in_svg > _svg_fills_and_strokes_in_svg
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/scripting_svg > _svg_scripting_svg
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/styling_svg_with_css > _svg_styling_svg_with_css
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/svg_clipping_and_masking > _svg_svg_clipping_and_masking
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/svg_filters > _svg_svg_filters
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/svg_fonts > _svg_svg_fonts
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/svg_gradients > _svg_svg_gradients
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/svg_image_element > _svg_svg_image_element
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/svg_introduction > _svg_svg_introduction
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/svg_links > _svg_svg_links
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/svg_pattern_fills > _svg_svg_pattern_fills
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/svg_primer > _svg_svg_primer
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/svg_syntax_and_deployment > _svg_svg_syntax_and_deployment
/Users/sierra/sandbox/webplatform/src/wpdget.pl get tutorials/using_text_in_svg > _svg_using_text_in_svg
