~/sandbox/webplatform/src/wpdget.pl get apis/css-regions > reg_css_regions_api.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/CSSRegionStyleRule > reg_CSSRegionStyleRule.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/Document/getNamedFlows > reg_getNamedFlows.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/NamedFlow > reg_NamedFlow.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/NamedFlow/firstEmptyRegionIndex > reg_firstEmptyRegionIndex.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/NamedFlow/getContent > reg_getContent.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/NamedFlow/getRegions > reg_getRegions.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/NamedFlow/getRegionsByContent > reg_getRegionsByContent.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/NamedFlow/name > reg_name.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/NamedFlow/overset > reg_overset.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/NamedFlow/regionlayoutupdate > reg_regionlayoutupdate.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/Region > reg_Region.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/Region/getComputedRegionStyle > reg_getComputedRegionStyle.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/Region/getRegionFlowRanges > reg_getRegionFlowRanges.txt
~/sandbox/webplatform/src/wpdget.pl get apis/css-regions/Region/regionOverset > reg_regionOverset.txt
~/sandbox/webplatform/src/wpdget.pl get css/atrules/@region > reg_at_region.txt
~/sandbox/webplatform/src/wpdget.pl get css/properties/break-after > reg_break_after.txt
~/sandbox/webplatform/src/wpdget.pl get css/properties/break-before > reg_break_before.txt
~/sandbox/webplatform/src/wpdget.pl get css/properties/break-inside > reg_break_inside.txt
~/sandbox/webplatform/src/wpdget.pl get css/properties/flow-from > reg_flow_from.txt
~/sandbox/webplatform/src/wpdget.pl get css/properties/flow-into > reg_flow_into.txt
~/sandbox/webplatform/src/wpdget.pl get css/properties/region-fragment > reg_region_fragment.txt
~/sandbox/webplatform/src/wpdget.pl get tutorials/css-regions > reg_css_regions_tut.txt
