~/sandbox/webplatform-tools/wpd edit css/atrules/@region "`cat at_region.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/break-after "`cat break_after.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/break-before "`cat break_before.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/break-inside "`cat break_inside.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/flow-from "`cat flow_from.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/flow-into "`cat flow_into.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/region-fragment "`cat region_fragment.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit tutorials/css-regions "`cat css_regions_tut.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions "`cat css_regions_api.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/CSSRegionStyleRule "`cat CSSRegionStyleRule.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/Document/getNamedFlows "`cat getNamedFlows.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow "`cat NamedFlow.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/firstEmptyRegionIndex "`cat firstEmptyRegionIndex.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/getContent "`cat getContent.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/getRegions "`cat getRegions.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/getRegionsByContent "`cat getRegionsByContent.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/name "`cat name.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/overset "`cat overset.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/regionlayoutupdate "`cat regionlayoutupdate.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/Region "`cat Region.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/Region/getComputedRegionStyle "`cat getComputedRegionStyle.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/Region/getRegionFlowRanges "`cat getRegionFlowRanges.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/Region/regionOverset "`cat regionOverset.txt`" -u Sierra
