~/sandbox/webplatform-tools/wpd edit css/atrules/@region "`cat reg_at_region.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/break-after "`cat reg_break_after.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/break-before "`cat reg_break_before.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/break-inside "`cat reg_break_inside.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/flow-from "`cat reg_flow_from.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/flow-into "`cat reg_flow_into.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit css/properties/region-fragment "`cat reg_region_fragment.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit tutorials/css-regions "`cat reg_css_regions_tut.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions "`cat reg_css_regions_api.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/CSSRegionStyleRule "`cat reg_CSSRegionStyleRule.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/Document/getNamedFlows "`cat reg_getNamedFlows.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow "`cat reg_NamedFlow.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/firstEmptyRegionIndex "`cat reg_firstEmptyRegionIndex.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/getContent "`cat reg_getContent.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/getRegions "`cat reg_getRegions.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/getRegionsByContent "`cat reg_getRegionsByContent.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/name "`cat reg_name.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/overset "`cat reg_overset.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/NamedFlow/regionlayoutupdate "`cat reg_regionlayoutupdate.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/Region "`cat reg_Region.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/Region/getComputedRegionStyle "`cat reg_getComputedRegionStyle.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/Region/getRegionFlowRanges "`cat reg_getRegionFlowRanges.txt`" -u Sierra
~/sandbox/webplatform-tools/wpd edit apis/css-regions/Region/regionOverset "`cat reg_regionOverset.txt`" -u Sierra
