./wpdget.pl check apis/webaudio
./wpdget.pl check apis/webaudio/AnalyserNode
./wpdget.pl check apis/webaudio/AnalyserNode/fftSize
./wpdget.pl check apis/webaudio/AnalyserNode/frequencyBinCount
./wpdget.pl check apis/webaudio/AnalyserNode/getByteFrequencyData
./wpdget.pl check apis/webaudio/AnalyserNode/getByteTimeDomainData
./wpdget.pl check apis/webaudio/AnalyserNode/getFloatFrequencyData
./wpdget.pl check apis/webaudio/AnalyserNode/maxDecibels
./wpdget.pl check apis/webaudio/AnalyserNode/minDecibels
./wpdget.pl check apis/webaudio/AnalyserNode/smoothingTimeConstant
./wpdget.pl check apis/webaudio/AudioBuffer
./wpdget.pl check apis/webaudio/AudioBuffer/duration
./wpdget.pl check apis/webaudio/AudioBuffer/getChannelData
./wpdget.pl check apis/webaudio/AudioBuffer/length
./wpdget.pl check apis/webaudio/AudioBuffer/numberOfChannels
./wpdget.pl check apis/webaudio/AudioBuffer/sampleRate
./wpdget.pl check apis/webaudio/AudioBufferSourceNode
./wpdget.pl check apis/webaudio/AudioBufferSourceNode/buffer
./wpdget.pl check apis/webaudio/AudioBufferSourceNode/loop
./wpdget.pl check apis/webaudio/AudioBufferSourceNode/loopEnd
./wpdget.pl check apis/webaudio/AudioBufferSourceNode/loopStart
./wpdget.pl check apis/webaudio/AudioBufferSourceNode/playbackRate
./wpdget.pl check apis/webaudio/AudioBufferSourceNode/playbackState
./wpdget.pl check apis/webaudio/AudioBufferSourceNode/start
./wpdget.pl check apis/webaudio/AudioBufferSourceNode/stop
./wpdget.pl check apis/webaudio/AudioContext
./wpdget.pl check apis/webaudio/AudioContext/activeSourceCount
./wpdget.pl check apis/webaudio/AudioContext/createAnalyser
./wpdget.pl check apis/webaudio/AudioContext/createBiquadFilter
./wpdget.pl check apis/webaudio/AudioContext/createBuffer
./wpdget.pl check apis/webaudio/AudioContext/createBufferSource
./wpdget.pl check apis/webaudio/AudioContext/createChannelMerger
./wpdget.pl check apis/webaudio/AudioContext/createChannelSplitter
./wpdget.pl check apis/webaudio/AudioContext/createConvolver
./wpdget.pl check apis/webaudio/AudioContext/createDelay
./wpdget.pl check apis/webaudio/AudioContext/createDynamicsCompressor
./wpdget.pl check apis/webaudio/AudioContext/createGain
./wpdget.pl check apis/webaudio/AudioContext/createMediaElementSource
./wpdget.pl check apis/webaudio/AudioContext/createMediaStreamSource
./wpdget.pl check apis/webaudio/AudioContext/createOscillator
./wpdget.pl check apis/webaudio/AudioContext/createPanner
./wpdget.pl check apis/webaudio/AudioContext/createScriptProcessor
./wpdget.pl check apis/webaudio/AudioContext/createWaveShaper
./wpdget.pl check apis/webaudio/AudioContext/createWaveTable
./wpdget.pl check apis/webaudio/AudioContext/currentTime
./wpdget.pl check apis/webaudio/AudioContext/decodeAudioData
./wpdget.pl check apis/webaudio/AudioContext/destination
./wpdget.pl check apis/webaudio/AudioContext/listener
./wpdget.pl check apis/webaudio/AudioContext/sampleRate
./wpdget.pl check apis/webaudio/AudioDestinationNode
./wpdget.pl check apis/webaudio/AudioDestinationNode/maxNumberOfChannels
./wpdget.pl check apis/webaudio/AudioDestinationNode/numberOfChannels
./wpdget.pl check apis/webaudio/AudioListener
./wpdget.pl check apis/webaudio/AudioListener/dopplerFactor
./wpdget.pl check apis/webaudio/AudioListener/setOrientation
./wpdget.pl check apis/webaudio/AudioListener/setPosition
./wpdget.pl check apis/webaudio/AudioListener/setVelocity
./wpdget.pl check apis/webaudio/AudioListener/speedOfSound
./wpdget.pl check apis/webaudio/AudioNode
./wpdget.pl check apis/webaudio/AudioNode/connect
./wpdget.pl check apis/webaudio/AudioNode/context
./wpdget.pl check apis/webaudio/AudioNode/disconnect
./wpdget.pl check apis/webaudio/AudioNode/numberOfInputs
./wpdget.pl check apis/webaudio/AudioNode/numberOfOutputs
./wpdget.pl check apis/webaudio/AudioParam
./wpdget.pl check apis/webaudio/AudioParam/cancelScheduledValues
./wpdget.pl check apis/webaudio/AudioParam/computedValue
./wpdget.pl check apis/webaudio/AudioParam/defaultValue
./wpdget.pl check apis/webaudio/AudioParam/exponentialRampToValueAtTime
./wpdget.pl check apis/webaudio/AudioParam/linearRampToValueAtTime
./wpdget.pl check apis/webaudio/AudioParam/maxValue
./wpdget.pl check apis/webaudio/AudioParam/minValue
./wpdget.pl check apis/webaudio/AudioParam/setTargetAtTime
./wpdget.pl check apis/webaudio/AudioParam/setValueAtTime
./wpdget.pl check apis/webaudio/AudioParam/setValueCurveAtTime
./wpdget.pl check apis/webaudio/AudioParam/value
./wpdget.pl check apis/webaudio/AudioProcessingEvent
./wpdget.pl check apis/webaudio/AudioProcessingEvent/inputBuffer
./wpdget.pl check apis/webaudio/AudioProcessingEvent/node
./wpdget.pl check apis/webaudio/AudioProcessingEvent/outputBuffer
./wpdget.pl check apis/webaudio/AudioProcessingEvent/playbackTime
./wpdget.pl check apis/webaudio/BiquadFilterNode
./wpdget.pl check apis/webaudio/BiquadFilterNode/Q
./wpdget.pl check apis/webaudio/BiquadFilterNode/frequency
./wpdget.pl check apis/webaudio/BiquadFilterNode/gain
./wpdget.pl check apis/webaudio/BiquadFilterNode/getFrequencyResponse
./wpdget.pl check apis/webaudio/BiquadFilterNode/type
./wpdget.pl check apis/webaudio/ConvolverNode
./wpdget.pl check apis/webaudio/ConvolverNode/buffer
./wpdget.pl check apis/webaudio/ConvolverNode/normalize
./wpdget.pl check apis/webaudio/DelayNode
./wpdget.pl check apis/webaudio/DelayNode/delayTime
./wpdget.pl check apis/webaudio/DynamicsCompressorNode
./wpdget.pl check apis/webaudio/DynamicsCompressorNode/attack
./wpdget.pl check apis/webaudio/DynamicsCompressorNode/knee
./wpdget.pl check apis/webaudio/DynamicsCompressorNode/ratio
./wpdget.pl check apis/webaudio/DynamicsCompressorNode/reduction
./wpdget.pl check apis/webaudio/DynamicsCompressorNode/release
./wpdget.pl check apis/webaudio/DynamicsCompressorNode/threshold
./wpdget.pl check apis/webaudio/GainNode
./wpdget.pl check apis/webaudio/GainNode/gain
./wpdget.pl check apis/webaudio/OscillatorNode
./wpdget.pl check apis/webaudio/OscillatorNode/detune
./wpdget.pl check apis/webaudio/OscillatorNode/frequency
./wpdget.pl check apis/webaudio/OscillatorNode/playbackState
./wpdget.pl check apis/webaudio/OscillatorNode/setWaveTable
./wpdget.pl check apis/webaudio/OscillatorNode/start
./wpdget.pl check apis/webaudio/OscillatorNode/stop
./wpdget.pl check apis/webaudio/OscillatorNode/type
./wpdget.pl check apis/webaudio/PannerNode
./wpdget.pl check apis/webaudio/PannerNode/coneInnerAngle
./wpdget.pl check apis/webaudio/PannerNode/coneOuterAngle
./wpdget.pl check apis/webaudio/PannerNode/coneOuterGain
./wpdget.pl check apis/webaudio/PannerNode/distanceModel
./wpdget.pl check apis/webaudio/PannerNode/maxDistance
./wpdget.pl check apis/webaudio/PannerNode/panningModel
./wpdget.pl check apis/webaudio/PannerNode/refDistance
./wpdget.pl check apis/webaudio/PannerNode/rolloffFactor
./wpdget.pl check apis/webaudio/PannerNode/setOrientation
./wpdget.pl check apis/webaudio/PannerNode/setPosition
./wpdget.pl check apis/webaudio/PannerNode/setVelocity
./wpdget.pl check apis/webaudio/ScriptProcessorNode
./wpdget.pl check apis/webaudio/ScriptProcessorNode/bufferSize
./wpdget.pl check apis/webaudio/ScriptProcessorNode/onaudioprocess
./wpdget.pl check apis/webaudio/WaveShaperNode
./wpdget.pl check apis/webaudio/WaveShaperNode/curve
