./wpdget.pl get apis/webaudio > webaudio.txt
./wpdget.pl get apis/webaudio/AnalyserNode > AnalyserNode.txt
./wpdget.pl get apis/webaudio/AnalyserNode/fftSize > AnalyserNode_fftSize.txt
./wpdget.pl get apis/webaudio/AnalyserNode/frequencyBinCount > AnalyserNode_frequencyBinCount.txt
./wpdget.pl get apis/webaudio/AnalyserNode/getByteFrequencyData > AnalyserNode_getByteFrequencyData.txt
./wpdget.pl get apis/webaudio/AnalyserNode/getByteTimeDomainData > AnalyserNode_getByteTimeDomainData.txt
./wpdget.pl get apis/webaudio/AnalyserNode/getFloatFrequencyData > AnalyserNode_getFloatFrequencyData.txt
./wpdget.pl get apis/webaudio/AnalyserNode/maxDecibels > AnalyserNode_maxDecibels.txt
./wpdget.pl get apis/webaudio/AnalyserNode/minDecibels > AnalyserNode_minDecibels.txt
./wpdget.pl get apis/webaudio/AnalyserNode/smoothingTimeConstant > AnalyserNode_smoothingTimeConstant.txt
./wpdget.pl get apis/webaudio/AudioBuffer > AudioBuffer.txt
./wpdget.pl get apis/webaudio/AudioBuffer/duration > AudioBuffer_duration.txt
./wpdget.pl get apis/webaudio/AudioBuffer/getChannelData > AudioBuffer_getChannelData.txt
./wpdget.pl get apis/webaudio/AudioBuffer/length > AudioBuffer_length.txt
./wpdget.pl get apis/webaudio/AudioBuffer/numberOfChannels > AudioBuffer_numberOfChannels.txt
./wpdget.pl get apis/webaudio/AudioBuffer/sampleRate > AudioBuffer_sampleRate.txt
./wpdget.pl get apis/webaudio/AudioBufferSourceNode > AudioBufferSourceNode.txt
./wpdget.pl get apis/webaudio/AudioBufferSourceNode/buffer > AudioBufferSourceNode_buffer.txt
./wpdget.pl get apis/webaudio/AudioBufferSourceNode/loop > AudioBufferSourceNode_loop.txt
./wpdget.pl get apis/webaudio/AudioBufferSourceNode/loopEnd > AudioBufferSourceNode_loopEnd.txt
./wpdget.pl get apis/webaudio/AudioBufferSourceNode/loopStart > AudioBufferSourceNode_loopStart.txt
./wpdget.pl get apis/webaudio/AudioBufferSourceNode/playbackRate > AudioBufferSourceNode_playbackRate.txt
./wpdget.pl get apis/webaudio/AudioBufferSourceNode/playbackState > AudioBufferSourceNode_playbackState.txt
./wpdget.pl get apis/webaudio/AudioBufferSourceNode/start > AudioBufferSourceNode_start.txt
./wpdget.pl get apis/webaudio/AudioBufferSourceNode/stop > AudioBufferSourceNode_stop.txt
./wpdget.pl get apis/webaudio/AudioContext > AudioContext.txt
./wpdget.pl get apis/webaudio/AudioContext/activeSourceCount > AudioContext_activeSourceCount.txt
./wpdget.pl get apis/webaudio/AudioContext/createAnalyser > AudioContext_createAnalyser.txt
./wpdget.pl get apis/webaudio/AudioContext/createBiquadFilter > AudioContext_createBiquadFilter.txt
./wpdget.pl get apis/webaudio/AudioContext/createBuffer > AudioContext_createBuffer.txt
./wpdget.pl get apis/webaudio/AudioContext/createBufferSource > AudioContext_createBufferSource.txt
./wpdget.pl get apis/webaudio/AudioContext/createChannelMerger > AudioContext_createChannelMerger.txt
./wpdget.pl get apis/webaudio/AudioContext/createChannelSplitter > AudioContext_createChannelSplitter.txt
./wpdget.pl get apis/webaudio/AudioContext/createConvolver > AudioContext_createConvolver.txt
./wpdget.pl get apis/webaudio/AudioContext/createDelay > AudioContext_createDelay.txt
./wpdget.pl get apis/webaudio/AudioContext/createDynamicsCompressor > AudioContext_createDynamicsCompressor.txt
./wpdget.pl get apis/webaudio/AudioContext/createGain > AudioContext_createGain.txt
./wpdget.pl get apis/webaudio/AudioContext/createMediaElementSource > AudioContext_createMediaElementSource.txt
./wpdget.pl get apis/webaudio/AudioContext/createMediaStreamSource > AudioContext_createMediaStreamSource.txt
./wpdget.pl get apis/webaudio/AudioContext/createOscillator > AudioContext_createOscillator.txt
./wpdget.pl get apis/webaudio/AudioContext/createPanner > AudioContext_createPanner.txt
./wpdget.pl get apis/webaudio/AudioContext/createScriptProcessor > AudioContext_createScriptProcessor.txt
./wpdget.pl get apis/webaudio/AudioContext/createWaveShaper > AudioContext_createWaveShaper.txt
./wpdget.pl get apis/webaudio/AudioContext/createWaveTable > AudioContext_createWaveTable.txt
./wpdget.pl get apis/webaudio/AudioContext/currentTime > AudioContext_currentTime.txt
./wpdget.pl get apis/webaudio/AudioContext/decodeAudioData > AudioContext_decodeAudioData.txt
./wpdget.pl get apis/webaudio/AudioContext/destination > AudioContext_destination.txt
./wpdget.pl get apis/webaudio/AudioContext/listener > AudioContext_listener.txt
./wpdget.pl get apis/webaudio/AudioContext/sampleRate > AudioContext_sampleRate.txt
./wpdget.pl get apis/webaudio/AudioDestinationNode > AudioDestinationNode.txt
./wpdget.pl get apis/webaudio/AudioDestinationNode/maxNumberOfChannels > AudioDestinationNode_maxNumberOfChannels.txt
./wpdget.pl get apis/webaudio/AudioDestinationNode/numberOfChannels > AudioDestinationNode_numberOfChannels.txt
./wpdget.pl get apis/webaudio/AudioListener > AudioListener.txt
./wpdget.pl get apis/webaudio/AudioListener/dopplerFactor > AudioListener_dopplerFactor.txt
./wpdget.pl get apis/webaudio/AudioListener/setOrientation > AudioListener_setOrientation.txt
./wpdget.pl get apis/webaudio/AudioListener/setPosition > AudioListener_setPosition.txt
./wpdget.pl get apis/webaudio/AudioListener/setVelocity > AudioListener_setVelocity.txt
./wpdget.pl get apis/webaudio/AudioListener/speedOfSound > AudioListener_speedOfSound.txt
./wpdget.pl get apis/webaudio/AudioNode > AudioNode.txt
./wpdget.pl get apis/webaudio/AudioNode/connect > AudioNode_connect.txt
./wpdget.pl get apis/webaudio/AudioNode/context > AudioNode_context.txt
./wpdget.pl get apis/webaudio/AudioNode/disconnect > AudioNode_disconnect.txt
./wpdget.pl get apis/webaudio/AudioNode/numberOfInputs > AudioNode_numberOfInputs.txt
./wpdget.pl get apis/webaudio/AudioNode/numberOfOutputs > AudioNode_numberOfOutputs.txt
./wpdget.pl get apis/webaudio/AudioParam > AudioParam.txt
./wpdget.pl get apis/webaudio/AudioParam/cancelScheduledValues > AudioParam_cancelScheduledValues.txt
./wpdget.pl get apis/webaudio/AudioParam/computedValue > AudioParam_computedValue.txt
./wpdget.pl get apis/webaudio/AudioParam/defaultValue > AudioParam_defaultValue.txt
./wpdget.pl get apis/webaudio/AudioParam/exponentialRampToValueAtTime > AudioParam_exponentialRampToValueAtTime.txt
./wpdget.pl get apis/webaudio/AudioParam/linearRampToValueAtTime > AudioParam_linearRampToValueAtTime.txt
./wpdget.pl get apis/webaudio/AudioParam/maxValue > AudioParam_maxValue.txt
./wpdget.pl get apis/webaudio/AudioParam/minValue > AudioParam_minValue.txt
./wpdget.pl get apis/webaudio/AudioParam/setTargetAtTime > AudioParam_setTargetAtTime.txt
./wpdget.pl get apis/webaudio/AudioParam/setValueAtTime > AudioParam_setValueAtTime.txt
./wpdget.pl get apis/webaudio/AudioParam/setValueCurveAtTime > AudioParam_setValueCurveAtTime.txt
./wpdget.pl get apis/webaudio/AudioParam/value > AudioParam_value.txt
./wpdget.pl get apis/webaudio/AudioProcessingEvent > AudioProcessingEvent.txt
./wpdget.pl get apis/webaudio/AudioProcessingEvent/inputBuffer > AudioProcessingEvent_inputBuffer.txt
./wpdget.pl get apis/webaudio/AudioProcessingEvent/node > AudioProcessingEvent_node.txt
./wpdget.pl get apis/webaudio/AudioProcessingEvent/outputBuffer > AudioProcessingEvent_outputBuffer.txt
./wpdget.pl get apis/webaudio/AudioProcessingEvent/playbackTime > AudioProcessingEvent_playbackTime.txt
./wpdget.pl get apis/webaudio/BiquadFilterNode > BiquadFilterNode.txt
./wpdget.pl get apis/webaudio/BiquadFilterNode/Q > BiquadFilterNode_Q.txt
./wpdget.pl get apis/webaudio/BiquadFilterNode/frequency > BiquadFilterNode_frequency.txt
./wpdget.pl get apis/webaudio/BiquadFilterNode/gain > BiquadFilterNode_gain.txt
./wpdget.pl get apis/webaudio/BiquadFilterNode/getFrequencyResponse > BiquadFilterNode_getFrequencyResponse.txt
./wpdget.pl get apis/webaudio/BiquadFilterNode/type > BiquadFilterNode_type.txt
./wpdget.pl get apis/webaudio/ConvolverNode > ConvolverNode.txt
./wpdget.pl get apis/webaudio/ConvolverNode/buffer > ConvolverNode_buffer.txt
./wpdget.pl get apis/webaudio/ConvolverNode/normalize > ConvolverNode_normalize.txt
./wpdget.pl get apis/webaudio/DelayNode > DelayNode.txt
./wpdget.pl get apis/webaudio/DelayNode/delayTime > DelayNode_delayTime.txt
./wpdget.pl get apis/webaudio/DynamicsCompressorNode > DynamicsCompressorNode.txt
./wpdget.pl get apis/webaudio/DynamicsCompressorNode/attack > DynamicsCompressorNode_attack.txt
./wpdget.pl get apis/webaudio/DynamicsCompressorNode/knee > DynamicsCompressorNode_knee.txt
./wpdget.pl get apis/webaudio/DynamicsCompressorNode/ratio > DynamicsCompressorNode_ratio.txt
./wpdget.pl get apis/webaudio/DynamicsCompressorNode/reduction > DynamicsCompressorNode_reduction.txt
./wpdget.pl get apis/webaudio/DynamicsCompressorNode/release > DynamicsCompressorNode_release.txt
./wpdget.pl get apis/webaudio/DynamicsCompressorNode/threshold > DynamicsCompressorNode_threshold.txt
./wpdget.pl get apis/webaudio/GainNode > GainNode.txt
./wpdget.pl get apis/webaudio/GainNode/gain > GainNode_gain.txt
./wpdget.pl get apis/webaudio/OscillatorNode > OscillatorNode.txt
./wpdget.pl get apis/webaudio/OscillatorNode/detune > OscillatorNode_detune.txt
./wpdget.pl get apis/webaudio/OscillatorNode/frequency > OscillatorNode_frequency.txt
./wpdget.pl get apis/webaudio/OscillatorNode/playbackState > OscillatorNode_playbackState.txt
./wpdget.pl get apis/webaudio/OscillatorNode/setWaveTable > OscillatorNode_setWaveTable.txt
./wpdget.pl get apis/webaudio/OscillatorNode/start > OscillatorNode_start.txt
./wpdget.pl get apis/webaudio/OscillatorNode/stop > OscillatorNode_stop.txt
./wpdget.pl get apis/webaudio/OscillatorNode/type > OscillatorNode_type.txt
./wpdget.pl get apis/webaudio/PannerNode > PannerNode.txt
./wpdget.pl get apis/webaudio/PannerNode/coneInnerAngle > PannerNode_coneInnerAngle.txt
./wpdget.pl get apis/webaudio/PannerNode/coneOuterAngle > PannerNode_coneOuterAngle.txt
./wpdget.pl get apis/webaudio/PannerNode/coneOuterGain > PannerNode_coneOuterGain.txt
./wpdget.pl get apis/webaudio/PannerNode/distanceModel > PannerNode_distanceModel.txt
./wpdget.pl get apis/webaudio/PannerNode/maxDistance > PannerNode_maxDistance.txt
./wpdget.pl get apis/webaudio/PannerNode/panningModel > PannerNode_panningModel.txt
./wpdget.pl get apis/webaudio/PannerNode/refDistance > PannerNode_refDistance.txt
./wpdget.pl get apis/webaudio/PannerNode/rolloffFactor > PannerNode_rolloffFactor.txt
./wpdget.pl get apis/webaudio/PannerNode/setOrientation > PannerNode_setOrientation.txt
./wpdget.pl get apis/webaudio/PannerNode/setPosition > PannerNode_setPosition.txt
./wpdget.pl get apis/webaudio/PannerNode/setVelocity > PannerNode_setVelocity.txt
./wpdget.pl get apis/webaudio/ScriptProcessorNode > ScriptProcessorNode.txt
./wpdget.pl get apis/webaudio/ScriptProcessorNode/bufferSize > ScriptProcessorNode_bufferSize.txt
./wpdget.pl get apis/webaudio/ScriptProcessorNode/onaudioprocess > ScriptProcessorNode_onaudioprocess.txt
./wpdget.pl get apis/webaudio/WaveShaperNode > WaveShaperNode.txt
./wpdget.pl get apis/webaudio/WaveShaperNode/curve > WaveShaperNode_curve.txt
